INSERT INTO  parent_table (
   SELECT
        'Employees' AS table_source,
		CURRENT_DATE() as load_date,
        emp_id,
        emp_name,
        emp_email,
        emp_salary,
        emp_join_date,
        emp_department,
        NULL::INT AS dept_id,
        NULL::VARCHAR AS dept_name,
        NULL::VARCHAR AS dept_location,
        NULL::VARCHAR AS dept_head,
        NULL::DECIMAL AS dept_budget,
        NULL::INT AS cust_id,
        NULL::VARCHAR AS cust_name,
        NULL::VARCHAR AS cust_email,
        NULL::VARCHAR AS cust_phone,
        NULL::VARCHAR AS cust_address,
        NULL::INT AS order_id,
        NULL::DATE AS order_date,
        NULL::DECIMAL AS order_amount,
        NULL::VARCHAR AS order_status,
        NULL::VARCHAR AS order_notes,
        NULL::INT AS product_id,
        NULL::VARCHAR AS product_name,
        NULL::VARCHAR AS product_category,
        NULL::DECIMAL AS product_price,
        NULL::INT AS product_stock
    FROM Employees

    UNION ALL

    SELECT
        'Departments' AS table_source,
		CURRENT_DATE as load_date,
        NULL::INT AS emp_id,
        NULL::VARCHAR AS emp_name,
        NULL::VARCHAR AS emp_email,
        NULL::DECIMAL AS emp_salary,
        NULL::DATE AS emp_join_date,
        NULL::VARCHAR AS emp_department,
        dept_id,
        dept_name,
        dept_location,
        dept_head,
        dept_budget,
        NULL::INT AS cust_id,
        NULL::VARCHAR AS cust_name,
        NULL::VARCHAR AS cust_email,
        NULL::VARCHAR AS cust_phone,
        NULL::VARCHAR AS cust_address,
        NULL::INT AS order_id,
        NULL::DATE AS order_date,
        NULL::DECIMAL AS order_amount,
        NULL::VARCHAR AS order_status,
        NULL::VARCHAR AS order_notes,
        NULL::INT AS product_id,
        NULL::VARCHAR AS product_name,
        NULL::VARCHAR AS product_category,
        NULL::DECIMAL AS product_price,
        NULL::INT AS product_stock
    FROM Departments

    UNION ALL

    SELECT
        'Customers' AS table_source,
		CURRENT_DATE as load_date,
        NULL::INT AS emp_id,
        NULL::VARCHAR AS emp_name,
        NULL::VARCHAR AS emp_email,
        NULL::DECIMAL AS emp_salary,
        NULL::DATE AS emp_join_date,
        NULL::VARCHAR AS emp_department,
        NULL::INT AS dept_id,
        NULL::VARCHAR AS dept_name,
        NULL::VARCHAR AS dept_location,
        NULL::VARCHAR AS dept_head,
        NULL::DECIMAL AS dept_budget,
        cust_id,
        cust_name,
        cust_email,
        cust_phone,
        cust_address,
        NULL::INT AS order_id,
        NULL::DATE AS order_date,
        NULL::DECIMAL AS order_amount,
        NULL::VARCHAR AS order_status,
        NULL::VARCHAR AS order_notes,
        NULL::INT AS product_id,
        NULL::VARCHAR AS product_name,
        NULL::VARCHAR AS product_category,
        NULL::DECIMAL AS product_price,
        NULL::INT AS product_stock
    FROM Customers

    UNION ALL

    SELECT
        'Orders' AS table_source,
		CURRENT_DATE as load_date,
        NULL::INT AS emp_id,
        NULL::VARCHAR AS emp_name,
        NULL::VARCHAR AS emp_email,
        NULL::DECIMAL AS emp_salary,
        NULL::DATE AS emp_join_date,
        NULL::VARCHAR AS emp_department,
        NULL::INT AS dept_id,
        NULL::VARCHAR AS dept_name,
        NULL::VARCHAR AS dept_location,
        NULL::VARCHAR AS dept_head,
        NULL::DECIMAL AS dept_budget,
        NULL::INT AS cust_id,
        NULL::VARCHAR AS cust_name,
        NULL::VARCHAR AS cust_email,
        NULL::VARCHAR AS cust_phone,
        NULL::VARCHAR AS cust_address,
        order_id,
        order_date,
        order_amount,
        order_status,
        order_notes,
        NULL::INT AS product_id,
        NULL::VARCHAR AS product_name,
        NULL::VARCHAR AS product_category,
        NULL::DECIMAL AS product_price,
        NULL::INT AS product_stock
    FROM Orders

    UNION ALL

    SELECT
        'Products' AS table_source,
		CURRENT_DATE as load_date,
        NULL::INT AS emp_id,
        NULL::VARCHAR AS emp_name,
        NULL::VARCHAR AS emp_email,
        NULL::DECIMAL AS emp_salary,
        NULL::DATE AS emp_join_date,
        NULL::VARCHAR AS emp_department,
        NULL::INT AS dept_id,
        NULL::VARCHAR AS dept_name,
        NULL::VARCHAR AS dept_location,
        NULL::VARCHAR AS dept_head,
        NULL::DECIMAL AS dept_budget,
        NULL::INT AS cust_id,
        NULL::VARCHAR AS cust_name,
        NULL::VARCHAR AS cust_email,
        NULL::VARCHAR AS cust_phone,
        NULL::VARCHAR AS cust_address,
        NULL::INT AS order_id,
        NULL::DATE AS order_date,
        NULL::DECIMAL AS order_amount,
        NULL::VARCHAR AS order_status,
        NULL::VARCHAR AS order_notes,
        product_id,
        product_name,
        product_category,
        product_price,
        product_stock
    FROM Products as p
);

/*
CREATE  TABLE parent_table (
    table_source VARCHAR,
	load_date DATE,
    emp_id INT,
    emp_name VARCHAR,
    emp_email VARCHAR,
    emp_salary DECIMAL,
    emp_join_date DATE,
    emp_department VARCHAR,
    dept_id INT,
    dept_name VARCHAR,
    dept_location VARCHAR,
    dept_head VARCHAR,
    dept_budget DECIMAL,
    cust_id INT,
    cust_name VARCHAR,
    cust_email VARCHAR,
    cust_phone VARCHAR,
    cust_address VARCHAR,
    order_id INT,
    order_date DATE,
    order_amount DECIMAL,
    order_status VARCHAR,
    order_notes VARCHAR,
    product_id INT,
    product_name VARCHAR,
    product_category VARCHAR,
    product_price DECIMAL,
    product_stock INT);
	*/