insert into parent_table (
select
'Employees' as table_source,
CURRENT_DATE AS LOAD_DATE , 
		emp_id,
		emp_name,
		emp_email,
		emp_salary,
		emp_join_date,
		emp_department,
NULL as dept_id,
NULL as dept_name,
NULL as dept_location,
NULL as dept_head,
NULL as dept_budget,
NULL as cust_id,
NULL as cust_name,
NULL as cust_email,
NULL as cust_phone,
NULL as cust_address,
NULL as order_id,
NULL as order_date,
NULL as order_amount,
NULL as order_status,
NULL as order_notes,
NULL as product_id,
NULL as product_name,
NULL as product_category,
NULL as product_price,
NULL as product_stock
from Employees
	union all 
select 
'Departments' as table_source ,
CURRENT_DATE AS LOAD_DATE, 
NULL as emp_id,
NULL as emp_name,
NULL as emp_email,
NULL as emp_salary,
NULL as	emp_join_date,
NULL as emp_department,
		dept_id,
		dept_name,
		dept_location,
		dept_head,
		dept_budget,
NULL as cust_id,
NULL as cust_name,
NULL as cust_email,
NULL as cust_phone,
NULL as cust_address,
NULL as order_id,
NULL as order_date,
NULL as order_amount,
NULL as order_status,
NULL as order_notes,
NULL as product_id,
NULL as product_name,
NULL as product_category,
NULL as product_price,
NULL as product_stock
from Departments
		union all  

select 
'Customers' as table_source ,
CURRENT_DATE AS LOAD_DATE, 
NULL as emp_id,
NULL as emp_name,
NULL as emp_email,
NULL as emp_salary,
NULL as	emp_join_date,
NULL as emp_department,
NULL as	dept_id,
NULL as	dept_name,
NULL as	dept_location,
NULL as	dept_head,
NULL as	dept_budget,
		cust_id,
		cust_name,
		cust_email,
		cust_phone,
		cust_address,
NULL as order_id,
NULL as order_date,
NULL as order_amount,
NULL as order_status,
NULL as order_notes,
NULL as product_id,
NULL as product_name,
NULL as product_category,
NULL as product_price,
NULL as product_stock
from Customers
		union all  
select 
'Orders' as table_source , 
CURRENT_DATE AS LOAD_DATE, 
NULL as emp_id,
NULL as emp_name,
NULL as emp_email,
NULL as emp_salary,
NULL as	emp_join_date,
NULL as emp_department,
NULL as	dept_id,
NULL as	dept_name,
NULL as	dept_location,
NULL as	dept_head,
NULL as	dept_budget,
NULL as cust_id,
NULL as cust_name,
NULL as cust_email,
NULL as cust_phone,
NULL as cust_address,
		order_id,
		order_date,
		order_amount,
		order_status,
		order_notes,
NULL as product_id,
NULL as product_name,
NULL as product_category,
NULL as product_price,
NULL as product_stock
from Orders
		union all 
		select 
'Products' as table_source ,
CURRENT_DATE AS LOAD_DATE, 
NULL as emp_id,
NULL as emp_name,
NULL as emp_email,
NULL as emp_salary,
NULL as	emp_join_date,
NULL as emp_department,
NULL as	dept_id,
NULL as	dept_name,
NULL as	dept_location,
NULL as	dept_head,
NULL as	dept_budget,
NULL as cust_id,
NULL as cust_name,
NULL as cust_email,
NULL as cust_phone,
NULL as cust_address,
NULL as	order_id,
NULL as	order_date,
NULL as	order_amount,
NULL as	order_status,
NULL as	order_notes,
		product_id,
		product_name,
		product_category,
		product_price,
		product_stock
from Products 
) 
CREATE TABLE  parent_table  (

table_source VARCHAR , 
LOAD_DATE DATE ,
		emp_id INT ,
		emp_name VARCHAR,
		emp_email VARCHAR,
		emp_salary DECIMAL,
		emp_join_date DATE,
		emp_department VARCHAR,
		dept_id INT,
		dept_name VARCHAR,
		dept_location VARCHAR,
		dept_head VARCHAR,
		dept_budget DECIMAL ,
		cust_id INT,	
		cust_name VARCHAR,
		cust_email	VARCHAR,
		cust_phone	VARCHAR,
		cust_address VARCHAR,
		order_id INT,
		order_date DATE,
		order_amount DECIMAL,
		order_status VARCHAR,
		order_notes VARCHAR,
		product_id INT,
		product_name VARCHAR,
		product_category VARCHAR,
		product_price DECIMAL,	
		product_stock INT
		) 


