INSERT INTO parent_table_fact_ac (
    table_source,
    emp_id,
	emp_name,
	emp_email,
	emp_salary,
	emp_join_date,
	emp_department,
    dept_id,
	dept_name,
	dept_location,
	dept_head,
	dept_budget,
    cust_id, 
	cust_name,
	cust_email,
	cust_phone,
	cust_address,
    order_id,
	order_date,
	order_amount,
	order_status,
	order_notes,
    product_id,
	product_name,
	product_category,
	product_price,
	product_stock,
    load_date
)
SELECT
    table_source,

    1.0 * SUM(CASE WHEN emp_id = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN emp_id <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN emp_name = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN emp_name <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN emp_email = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN emp_email <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN emp_salary = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN emp_salary <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN emp_join_date = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN emp_join_date <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN emp_department = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN emp_department <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN dept_id = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN dept_id <> 'NA' THEN 1 else null  END),
    1.0 * SUM(CASE WHEN dept_name = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN dept_name <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN dept_location = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN dept_location <> 'NA' THEN 1 else null  END),
    1.0 * SUM(CASE WHEN dept_head = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN dept_head <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN dept_budget = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN dept_budget <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN cust_id = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN cust_id <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN cust_name = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN cust_name <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN cust_email = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN cust_email <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN cust_phone = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN cust_phone <> 'NA' THEN 1 else null  END),
    1.0 * SUM(CASE WHEN cust_address = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN cust_address <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN order_id = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN order_id <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN order_date = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN order_date <> 'NA' THEN 1 else null  END),
    1.0 * SUM(CASE WHEN order_amount = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN order_amount <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN order_status = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN order_status <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN order_notes = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN order_notes <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN product_id = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN product_id <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN product_name = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN product_name <> 'NA' THEN 1  else null END),
    1.0 * SUM(CASE WHEN product_category = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN product_category <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN product_price = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN product_price <> 'NA' THEN 1 else null END),
    1.0 * SUM(CASE WHEN product_stock = '1' THEN 1 ELSE 0 END) / COUNT(CASE WHEN product_stock <> 'NA' THEN 1  else null END),

    CURRENT_DATE AS load_date
FROM parent_table_Accuracy
GROUP BY table_source
 



/*CREATE TABLE parent_table_fact_ac(
    table_source   VARCHAR,
    emp_id NUMERIC(10,4),
    emp_name NUMERIC(10,4),
    emp_email NUMERIC(10,4),
    emp_salary NUMERIC(10,4),
    emp_join_date NUMERIC(10,4),
    emp_department NUMERIC(10,4),
    dept_id NUMERIC(10,4),
    dept_name NUMERIC(10,4),
    dept_location NUMERIC(10,4),
    dept_head NUMERIC(10,4),
    dept_budget NUMERIC(10,4),
    cust_id NUMERIC(10,4),
    cust_name NUMERIC(10,4),
    cust_email NUMERIC(10,4),
    cust_phone NUMERIC(10,4),
    cust_address NUMERIC(10,4),
    order_id NUMERIC(10,4),
    order_date NUMERIC(10,4),
    order_amount NUMERIC(10,4),
    order_status NUMERIC(10,4),
    order_notes NUMERIC(10,4),
    product_id NUMERIC(10,4),
    product_name NUMERIC(10,4),
    product_category NUMERIC(10,4),
    product_price NUMERIC(10,4),
    product_stock NUMERIC(10,4),
	load_date DATE
);